apiVersion: v1
kind: Service
metadata:
  name: go-kubernetes-service # Название нашего объекта Service
spec:
  # ClusterIP - сервис доступен только внутри кластера по внутреннему IP.
  # Это тип по умолчанию. Для доступа извне позже воспользуемся port-forward.
  type: ClusterIP
  selector:
    # Service будет искать Pod'ы с этой меткой ('app=go-kubernetes')
    # и направлять трафик на них. Метка должна совпадать с меткой Pod'ов из Deployment'а.
    app: go-kubernetes
  ports:
    - protocol: TCP
      # Порт, на котором будет доступен сам Service внутри кластера.
      # Можно выбрать стандартный порт 80 для HTTP.
      port: 80
      # Порт на контейнере (containerPort из Deployment'а), на который будет идти трафик.
      targetPort: 8080